# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, null=True)),
                ('label', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('registration_datetime', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=10, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Card')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Device')),
            ],
        ),
        migrations.AddField(
            model_name='duration',
            name='registration_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Registration'),
        ),
        migrations.AddField(
            model_name='duration',
            name='registration_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration2registration_out', to='main.Registration'),
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
    ]
