# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='registration',
            name='img',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
